// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3c8XfvXqnWY2L3w_W0zME4bZLG6GbCY',
    appId: '1:95753080454:web:1ffbfcfd46cea00d224b07',
    messagingSenderId: '95753080454',
    projectId: 'seven-manager-a3de1',
    authDomain: 'seven-manager-a3de1.firebaseapp.com',
    storageBucket: 'seven-manager-a3de1.appspot.com',
    measurementId: 'G-TJRRSWQYKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PekFLC7RWTNk9e-y2vcVTP_PStE7nJs',
    appId: '1:95753080454:android:506524258145946b224b07',
    messagingSenderId: '95753080454',
    projectId: 'seven-manager-a3de1',
    storageBucket: 'seven-manager-a3de1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr3c8XfvXqnWY2L3w_W0zME4bZLG6GbCY',
    appId: '1:95753080454:web:d9e4f74baf3d9dfa224b07',
    messagingSenderId: '95753080454',
    projectId: 'seven-manager-a3de1',
    authDomain: 'seven-manager-a3de1.firebaseapp.com',
    storageBucket: 'seven-manager-a3de1.appspot.com',
    measurementId: 'G-Y6JHYCR7XQ',
  );
}
